name: 'decamp_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  decamp_project:
    +schema: grocery_data
    # Applies to all files under models/name_of_model/
    silver_layer:
      +schema: silver_layer
      materialized: view
    gold_layer:
      +schema: gold_layer
      materialized: table

seeds:
  decamp_project:
    +schema: grocery_data
    categories:
      +column_types:
        CategoryID: integer
        CategoryName: string
    cities:
      +column_types:
        CityID: integer
        CityName: string
        Zipcode: float
        CountryID: integer
    countries:
      +column_types:
        CountryID: integer
        CountryName: string
        CountryCode: string

vars:
  is_test_run: false